name: Scheduled B-2

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Request 2
        run: |
          c=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.SCHEDULED_3 }}")
          if [ "$c" -lt 200 ] || [ "$c" -ge 300 ]; then exit 1; fi
